name: "Centum Docs"

baseurl: "/centum"

copyright: "2021-2025 <a href=\"https://sidroberts.co.uk/\">Sid Roberts</a>"

gh_repository:      "SidRoberts/centum"
gh_dir:             "docs"
gh_branch:          "main"
gh_edit_view_mode:  "edit"

include:
  - _assets
