name: docs-lint

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install NPM
      uses: actions/setup-node@v2
    - name: Install markdownlint-cli
      run: npm install -g markdownlint-cli
    - name: Run markdownlint-cli
      run: markdownlint docs/
