name: tests

on: push

jobs:
  codeception:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1', '8.2']
    steps:
    - uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: yaml
        tools: composer:v2
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Run test suite
      run: vendor/bin/codecept run
  psalm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1', '8.2']
    steps:
    - uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: yaml
        tools: composer:v2
    - name: Validate composer.json and composer.lock
      run: composer validate
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Build Codeception
      run: vendor/bin/codecept build
    - name: Run psalm
      run: vendor/bin/psalm
